# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainwindowUI.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainwindowUI(object):
    def setupUi(self, MainwindowUI):
        MainwindowUI.setObjectName(_fromUtf8("MainwindowUI"))
        MainwindowUI.resize(892, 749)
        MainwindowUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainwindowUI.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainwindowUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.logging_button_panel = QtGui.QGridLayout()
        self.logging_button_panel.setObjectName(_fromUtf8("logging_button_panel"))
        self.start_logging_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_logging_button.setFont(font)
        self.start_logging_button.setObjectName(_fromUtf8("start_logging_button"))
        self.logging_button_panel.addWidget(self.start_logging_button, 0, 0, 1, 1)
        self.stop_logging_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop_logging_button.setFont(font)
        self.stop_logging_button.setObjectName(_fromUtf8("stop_logging_button"))
        self.logging_button_panel.addWidget(self.stop_logging_button, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.logging_button_panel, 6, 0, 1, 1)
        self.application_title = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.application_title.setFont(font)
        self.application_title.setObjectName(_fromUtf8("application_title"))
        self.gridLayout.addWidget(self.application_title, 0, 0, 1, 1)
        self.level_display_area = QtGui.QScrollArea(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.level_display_area.setPalette(palette)
        self.level_display_area.setWidgetResizable(True)
        self.level_display_area.setObjectName(_fromUtf8("level_display_area"))
        self.level_display_area_layout = QtGui.QWidget()
        self.level_display_area_layout.setGeometry(QtCore.QRect(0, 0, 872, 405))
        self.level_display_area_layout.setObjectName(_fromUtf8("level_display_area_layout"))
        self.gridLayout_3 = QtGui.QGridLayout(self.level_display_area_layout)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.level_display_grid = QtGui.QGridLayout()
        self.level_display_grid.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.level_display_grid.setObjectName(_fromUtf8("level_display_grid"))
        self.ln2_unit_label = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ln2_unit_label.setFont(font)
        self.ln2_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ln2_unit_label.setObjectName(_fromUtf8("ln2_unit_label"))
        self.level_display_grid.addWidget(self.ln2_unit_label, 4, 3, 1, 1)
        self.log_interval_textbox = QtGui.QLineEdit(self.level_display_area_layout)
        self.log_interval_textbox.setMaximumSize(QtCore.QSize(75, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_interval_textbox.setFont(font)
        self.log_interval_textbox.setObjectName(_fromUtf8("log_interval_textbox"))
        self.level_display_grid.addWidget(self.log_interval_textbox, 5, 4, 1, 1)
        self.log_interval_unit_label = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_interval_unit_label.setFont(font)
        self.log_interval_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.log_interval_unit_label.setObjectName(_fromUtf8("log_interval_unit_label"))
        self.level_display_grid.addWidget(self.log_interval_unit_label, 5, 3, 1, 1)
        self.log_interval_display = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.log_interval_display.setFont(font)
        self.log_interval_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.log_interval_display.setObjectName(_fromUtf8("log_interval_display"))
        self.level_display_grid.addWidget(self.log_interval_display, 5, 2, 1, 1)
        self.lhe_level_display = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lhe_level_display.setFont(font)
        self.lhe_level_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lhe_level_display.setObjectName(_fromUtf8("lhe_level_display"))
        self.level_display_grid.addWidget(self.lhe_level_display, 3, 2, 1, 1)
        self.log_interval_label = QtGui.QLabel(self.level_display_area_layout)
        self.log_interval_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_interval_label.setFont(font)
        self.log_interval_label.setAlignment(QtCore.Qt.AlignCenter)
        self.log_interval_label.setObjectName(_fromUtf8("log_interval_label"))
        self.level_display_grid.addWidget(self.log_interval_label, 5, 0, 1, 1)
        self.value_section_title = QtGui.QLabel(self.level_display_area_layout)
        self.value_section_title.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.value_section_title.setFont(font)
        self.value_section_title.setAlignment(QtCore.Qt.AlignCenter)
        self.value_section_title.setObjectName(_fromUtf8("value_section_title"))
        self.level_display_grid.addWidget(self.value_section_title, 0, 2, 1, 1)
        self.lhe_level_unit_label = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lhe_level_unit_label.setFont(font)
        self.lhe_level_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lhe_level_unit_label.setObjectName(_fromUtf8("lhe_level_unit_label"))
        self.level_display_grid.addWidget(self.lhe_level_unit_label, 3, 3, 1, 1)
        self.ln2_level_display = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ln2_level_display.setFont(font)
        self.ln2_level_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ln2_level_display.setObjectName(_fromUtf8("ln2_level_display"))
        self.level_display_grid.addWidget(self.ln2_level_display, 4, 2, 1, 1)
        self.go_section_title = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.go_section_title.setFont(font)
        self.go_section_title.setAlignment(QtCore.Qt.AlignCenter)
        self.go_section_title.setObjectName(_fromUtf8("go_section_title"))
        self.level_display_grid.addWidget(self.go_section_title, 0, 5, 1, 1)
        self.liquid_helium_label = QtGui.QLabel(self.level_display_area_layout)
        self.liquid_helium_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.liquid_helium_label.setFont(font)
        self.liquid_helium_label.setAlignment(QtCore.Qt.AlignCenter)
        self.liquid_helium_label.setObjectName(_fromUtf8("liquid_helium_label"))
        self.level_display_grid.addWidget(self.liquid_helium_label, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.level_display_area_layout)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.level_display_grid.addWidget(self.label_9, 2, 0, 1, 1)
        self.blank_label = QtGui.QLabel(self.level_display_area_layout)
        self.blank_label.setText(_fromUtf8(""))
        self.blank_label.setObjectName(_fromUtf8("blank_label"))
        self.level_display_grid.addWidget(self.blank_label, 0, 0, 1, 1)
        self.magnetic_field_unit_label = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.magnetic_field_unit_label.setFont(font)
        self.magnetic_field_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.magnetic_field_unit_label.setObjectName(_fromUtf8("magnetic_field_unit_label"))
        self.level_display_grid.addWidget(self.magnetic_field_unit_label, 2, 3, 1, 1)
        self.current_title = QtGui.QLabel(self.level_display_area_layout)
        self.current_title.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_title.setFont(font)
        self.current_title.setAlignment(QtCore.Qt.AlignCenter)
        self.current_title.setObjectName(_fromUtf8("current_title"))
        self.level_display_grid.addWidget(self.current_title, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.level_display_grid.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.level_display_area_layout)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.level_display_grid.addWidget(self.label_6, 0, 3, 1, 1)
        self.liquid_nitrogen_label = QtGui.QLabel(self.level_display_area_layout)
        self.liquid_nitrogen_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.liquid_nitrogen_label.setFont(font)
        self.liquid_nitrogen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.liquid_nitrogen_label.setObjectName(_fromUtf8("liquid_nitrogen_label"))
        self.level_display_grid.addWidget(self.liquid_nitrogen_label, 4, 0, 1, 1)
        self.log_interval_go_button = QtGui.QPushButton(self.level_display_area_layout)
        self.log_interval_go_button.setMinimumSize(QtCore.QSize(100, 65))
        self.log_interval_go_button.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_interval_go_button.setFont(font)
        self.log_interval_go_button.setObjectName(_fromUtf8("log_interval_go_button"))
        self.level_display_grid.addWidget(self.log_interval_go_button, 5, 5, 1, 1)
        self.main_current_display = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.main_current_display.setFont(font)
        self.main_current_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_current_display.setObjectName(_fromUtf8("main_current_display"))
        self.level_display_grid.addWidget(self.main_current_display, 1, 2, 1, 1)
        self.magnetic_field_display = QtGui.QLabel(self.level_display_area_layout)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.magnetic_field_display.setFont(font)
        self.magnetic_field_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.magnetic_field_display.setObjectName(_fromUtf8("magnetic_field_display"))
        self.level_display_grid.addWidget(self.magnetic_field_display, 2, 2, 1, 1)
        self.current_unit_label = QtGui.QLabel(self.level_display_area_layout)
        self.current_unit_label.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_unit_label.setFont(font)
        self.current_unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_unit_label.setObjectName(_fromUtf8("current_unit_label"))
        self.level_display_grid.addWidget(self.current_unit_label, 1, 3, 1, 1)
        self.gridLayout_3.addLayout(self.level_display_grid, 0, 0, 1, 1)
        self.level_display_area.setWidget(self.level_display_area_layout)
        self.gridLayout.addWidget(self.level_display_area, 1, 0, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 872, 197))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.set_upper_sweep_current_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.set_upper_sweep_current_button.setFont(font)
        self.set_upper_sweep_current_button.setObjectName(_fromUtf8("set_upper_sweep_current_button"))
        self.gridLayout_7.addWidget(self.set_upper_sweep_current_button, 0, 2, 1, 1)
        self.lower_sweep_limit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lower_sweep_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lower_sweep_limit.setObjectName(_fromUtf8("lower_sweep_limit"))
        self.gridLayout_7.addWidget(self.lower_sweep_limit, 1, 1, 1, 1)
        self.upper_sweep_limit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.upper_sweep_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.upper_sweep_limit.setObjectName(_fromUtf8("upper_sweep_limit"))
        self.gridLayout_7.addWidget(self.upper_sweep_limit, 0, 1, 1, 1)
        self.set_lower_sweep_current_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.set_lower_sweep_current_button.setFont(font)
        self.set_lower_sweep_current_button.setObjectName(_fromUtf8("set_lower_sweep_current_button"))
        self.gridLayout_7.addWidget(self.set_lower_sweep_current_button, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sweep_up_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sweep_up_button.setFont(font)
        self.sweep_up_button.setObjectName(_fromUtf8("sweep_up_button"))
        self.verticalLayout.addWidget(self.sweep_up_button)
        self.sweep_zero_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sweep_zero_button.setFont(font)
        self.sweep_zero_button.setObjectName(_fromUtf8("sweep_zero_button"))
        self.verticalLayout.addWidget(self.sweep_zero_button)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stop_sweep_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stop_sweep_button.setFont(font)
        self.stop_sweep_button.setObjectName(_fromUtf8("stop_sweep_button"))
        self.verticalLayout_2.addWidget(self.stop_sweep_button)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 3, 0, 1, 1)
        MainwindowUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainwindowUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainwindowUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainwindowUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainwindowUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainwindowUI)
        QtCore.QMetaObject.connectSlotsByName(MainwindowUI)

    def retranslateUi(self, MainwindowUI):
        MainwindowUI.setWindowTitle(_translate("MainwindowUI", "Cryogenics System Monitor and Control", None))
        self.start_logging_button.setText(_translate("MainwindowUI", "Start Logging", None))
        self.stop_logging_button.setText(_translate("MainwindowUI", "Stop Logging", None))
        self.application_title.setText(_translate("MainwindowUI", "Cryomagnetics System Monitor and Control", None))
        self.ln2_unit_label.setText(_translate("MainwindowUI", "cm", None))
        self.log_interval_unit_label.setText(_translate("MainwindowUI", "min", None))
        self.log_interval_display.setText(_translate("MainwindowUI", "0", None))
        self.lhe_level_display.setText(_translate("MainwindowUI", "0", None))
        self.log_interval_label.setText(_translate("MainwindowUI", "Log Interval", None))
        self.value_section_title.setText(_translate("MainwindowUI", "Now", None))
        self.lhe_level_unit_label.setText(_translate("MainwindowUI", "cm", None))
        self.ln2_level_display.setText(_translate("MainwindowUI", "0", None))
        self.go_section_title.setText(_translate("MainwindowUI", "Go", None))
        self.liquid_helium_label.setText(_translate("MainwindowUI", "LHe Level", None))
        self.label_9.setText(_translate("MainwindowUI", "Magnetic Field", None))
        self.magnetic_field_unit_label.setText(_translate("MainwindowUI", "G", None))
        self.current_title.setText(_translate("MainwindowUI", "Main Current", None))
        self.label_7.setText(_translate("MainwindowUI", "Set", None))
        self.liquid_nitrogen_label.setText(_translate("MainwindowUI", "LN2 Level", None))
        self.log_interval_go_button.setText(_translate("MainwindowUI", "Go", None))
        self.main_current_display.setText(_translate("MainwindowUI", "0", None))
        self.magnetic_field_display.setText(_translate("MainwindowUI", "0", None))
        self.current_unit_label.setText(_translate("MainwindowUI", "A", None))
        self.set_upper_sweep_current_button.setText(_translate("MainwindowUI", "Set", None))
        self.lower_sweep_limit.setText(_translate("MainwindowUI", "0", None))
        self.upper_sweep_limit.setText(_translate("MainwindowUI", "0", None))
        self.set_lower_sweep_current_button.setText(_translate("MainwindowUI", "Set", None))
        self.label_8.setText(_translate("MainwindowUI", "Upper Limit", None))
        self.label_19.setText(_translate("MainwindowUI", "Lower Limit", None))
        self.sweep_up_button.setText(_translate("MainwindowUI", "Sweep Up", None))
        self.sweep_zero_button.setText(_translate("MainwindowUI", "Sweep Zero", None))
        self.pushButton_3.setText(_translate("MainwindowUI", "Sweep Down", None))
        self.stop_sweep_button.setText(_translate("MainwindowUI", "Stop Sweep", None))

