# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainwindowUI.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainwindowUI(object):
    def setupUi(self, MainwindowUI):
        MainwindowUI.setObjectName(_fromUtf8("MainwindowUI"))
        MainwindowUI.resize(890, 623)
        MainwindowUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainwindowUI.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainwindowUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 870, 498))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setMaximumSize(QtCore.QSize(75, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 6, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lcdNumber_6 = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber_6.setDigitCount(10)
        self.lcdNumber_6.setProperty("intValue", 15)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.gridLayout_2.addWidget(self.lcdNumber_6, 6, 1, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 65))
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lcdNumber_2.setDigitCount(10)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 65))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 65))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 1, 4, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 6, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 5, 2, 1, 1)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber_5.setMinimumSize(QtCore.QSize(0, 65))
        self.lcdNumber_5.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lcdNumber_5.setDigitCount(10)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_5, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 2, 1, 1)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber_4.setMinimumSize(QtCore.QSize(0, 65))
        self.lcdNumber_4.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lcdNumber_4.setNumDigits(10)
        self.lcdNumber_4.setDigitCount(10)
        self.lcdNumber_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_4.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_4, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 2, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcdNumber_3.setMinimumSize(QtCore.QSize(0, 65))
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lcdNumber_3.setDigitCount(10)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_3, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 65))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 6, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        MainwindowUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainwindowUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainwindowUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainwindowUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainwindowUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainwindowUI)
        QtCore.QMetaObject.connectSlotsByName(MainwindowUI)

    def retranslateUi(self, MainwindowUI):
        MainwindowUI.setWindowTitle(_translate("MainwindowUI", "Cryogenics System Monitor and Control", None))
        self.label.setText(_translate("MainwindowUI", "Cryomagnetics System Monitor and Control", None))
        self.label_2.setText(_translate("MainwindowUI", "Main Current", None))
        self.label_4.setText(_translate("MainwindowUI", "A", None))
        self.label_5.setText(_translate("MainwindowUI", "Now", None))
        self.label_8.setText(_translate("MainwindowUI", "Sweep Current", None))
        self.label_14.setText(_translate("MainwindowUI", "A", None))
        self.label_13.setText(_translate("MainwindowUI", "Go", None))
        self.label_7.setText(_translate("MainwindowUI", "Set", None))
        self.pushButton.setText(_translate("MainwindowUI", "Go", None))
        self.pushButton_3.setText(_translate("MainwindowUI", "Go", None))
        self.label_12.setText(_translate("MainwindowUI", "Log Interval", None))
        self.label_17.setText(_translate("MainwindowUI", "cm", None))
        self.label_11.setText(_translate("MainwindowUI", "LN2 Level", None))
        self.label_16.setText(_translate("MainwindowUI", "cm", None))
        self.label_10.setText(_translate("MainwindowUI", "LHe Level", None))
        self.label_15.setText(_translate("MainwindowUI", "G", None))
        self.label_9.setText(_translate("MainwindowUI", "Magnetic Field", None))
        self.pushButton_2.setText(_translate("MainwindowUI", "Go", None))
        self.label_18.setText(_translate("MainwindowUI", "min", None))
        self.pushButton_4.setText(_translate("MainwindowUI", "Start Logging", None))
        self.pushButton_5.setText(_translate("MainwindowUI", "Stop Logging", None))

