sudo: false

language: python

cache: pip

python:
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  - nosetests ./tests/unit --with-coverage # Run unit tests

  # This test tests the CSV writer. It should be safe to run on travis
  - nosetests ./tests/integration/test_resources/test_csv_file.py --with-coverage

after_success:
  - coveralls
