sudo: false

language: python

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

notifications:
  email: false

before_install:
  - mkdir install-images
  - cd install-images
  - wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.2/sip-4.19.2.tar.gz/download
  - tar -xzf download
  - rm download
  - wget https://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.12/PyQt4_gpl_x11-4.12.tar.gz/download
  - tar -xzf download
  - rm download
  - cd ..

install:
  - cd install-images
  - cd sip-4.19.2
  - python configure.py
  - make
  - make install
  - cd ..
  - cd PyQt4_gpl_x11-4.12
  - python configure-ng.py
  - make
  - make install
  - cd ..

script:
  - nosetests ./tests/unit --with-coverage # Run unit tests

  # This test tests the CSV writer. It should be safe to run on travis
  - nosetests ./tests/integration/test_resources/test_csv_file.py --with-coverage
  # Test the JSON pipe writer.
  - nosetests ./tests/integration/test_resources/test_pipe.py --with-coverage

after_success:
  - coveralls
