sudo: false

language: python

cache: pip

python:
  - "3.2"
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage

after_success:
  - coveralls
